[package]
name = "acebau-cli"
version.workspace = true
edition.workspace = true

[dependencies]
acebau-activity = { workspace = true }
acebau-catalogue = { workspace = true }
acebau-database = { workspace = true }
acebau-files = { workspace = true }
acebau-finance = { workspace = true }
acebau-inventory = { workspace = true }
acebau-invoice = { workspace = true }
acebau-machine = { workspace = true }
acebau-order = { workspace = true }
acebau-part = { workspace = true }
acebau-production = { workspace = true }
acebau-recipe = { workspace = true }
acebau-reseller = { workspace = true }
acebau-settings = { workspace = true }
clap = { workspace = true, features = ["env"] }
clap-config-fallback = { workspace = true }
serde = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread"] }
url = { workspace = true, features = ["serde"] }
