[package]
name = "acebau-api"
version = "0.1.0"
edition.workspace = true

[features]
default = []

[dependencies]
acebau-database = { workspace = true }
clap = { workspace = true, features = ["env"] }
clap-config-fallback = { workspace = true }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true, features = ["serde"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tower-http = { workspace = true, features = ["cors"] }

[dev-dependencies]
sqlx = { workspace = true, features = ["postgres"] }
