[package]
name = "acebau-unit-derive"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = "1"
quote = "1"
darling = "0.21"
derive_more = { workspace = true, features = ["from"] }
heck = "0.5.0"
