[package]
name = "acebau-core"
version = "0.1.0"
edition.workspace = true

[features]
default = []
sqlx = ["dep:sqlx"]
serde = ["dep:serde"]

[dependencies]
snafu = { workspace = true }
num = "0.4.3"
serde = { version = "1.0.218", features = ["derive"], optional = true }
sqlx = { version = "0.8.3", default-features = false, optional = true }
