[package]
name = "acebau-server"
version = "0.1.0"
edition.workspace = true

[features]
default = []

[dependencies]
acebau-unit = { workspace = true, features = ["serde", "sqlx"] }
acebau-database = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["env"] }
clap-config-fallback = { workspace = true }
snafu = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
url = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tower-http = { workspace = true, features = ["cors"] }

[dev-dependencies]
sqlx = { workspace = true, features = ["postgres"] }
