[package]
name = "acebau-database"
version = "0.1.0"
edition.workspace = true

[features]
default = []
serde = ["dep:serde", "chrono/serde"]

[dependencies]
acebau-core = { workspace = true, features = ["sqlx", "serde"] }
chrono = { workspace = true }
derive_more = { workspace = true, features = ["deref", "deref_mut", "display", "from"] }
snafu = { workspace = true }
serde = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"] }
url = { workspace = true }
sqlx = { workspace = true, features = ["chrono", "uuid", "postgres"] }
strum = { workspace = true, features = ["derive"] }
